name: Deploy Battle Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t royal-arena-server:latest .

      - name: Compress Docker Image
        run: docker save -o server-image.tar royal-arena-server:latest

      - name: Transfer Image to Production Server
        # Adapte l'IP, l'utilisateur et le chemin selon les directives du Sys Admin (ici 10.0.0.54 et /opt/royal-arena-server/)
        run: scp -o StrictHostKeyChecking=no server-image.tar docker-compose.yml royal-arena-server@10.0.0.54:/opt/royal-arena-server/

      - name: Deploy on Production Server
        run: |
          ssh -o StrictHostKeyChecking=no royal-arena-server@10.0.0.53 << 'EOF'
            cd /opt/royal-arena-server
            docker load -i server-image.tar
            docker compose up -d
            rm server-image.tar
            docker image prune -f
          EOF
